import { useState } from "react";
import type { MouseEventHandler } from "react";
import Head from "next/head";
import { LazyImage } from "@/components/LazyImage";

// Generate a random number between 1 and 123
const random = (): number => Math.floor(Math.random() * 123) + 1;

// Generate simple unique id
const generateId = () => Math.random().toString(36).split(".")[1];

export interface ImageItems {
  id: string;
  url: string;
}

export default function Home() {
  const [images, setImages] = useState<ImageItems[]>([]);

  const addNewFox: MouseEventHandler<HTMLButtonElement> = (event): void => {
    event.preventDefault();

    const target = event.target;

    const newImageItem: ImageItems = {
      id: generateId(),
      url: `https://randomfox.ca/images/${random()}.jpg`,
    };

    setImages([...images, newImageItem]);
  };

  return (
    <>
      <Head>
        <title>React TS Course</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="text-3xl font-extrabold text-center underline uppercase">
          Hello, Platzi!
        </h1>
        <p className="p-4">
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt
          obcaecati quia cupiditate fugiat, omnis molestias dolore temporibus
          doloremque itaque vel voluptatem qui quidem doloribus, sapiente,
          laborum rem atque numquam quos!
        </p>

        <button
          onClick={addNewFox}
          className="flex items-center justify-center px-3 py-1 mx-auto my-5 text-white bg-blue-600 rounded-md hover:bg-blue-800"
        >
          ADD NEW FOX
        </button>
        {images?.map(({ id, url }) => (
          <div key={id} className="p-4">
            <LazyImage
              src={url}
              alt={`Fox image ${id}`}
              onClick={(e) => console.log(e)}
              width={320}
              height={"auto"}
              className="mx-auto my-5 rounded-md bg-slate-100"
            />
          </div>
        ))}
        {}
      </main>
    </>
  );
}
